version: '3.9'
services:
  server:
    build:
      context: .
      target: hb_back
    image: hb_backend:latest
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8085:8080
    depends_on:
      - db

  client:
    build:
      context: .
      target: hb_front
    image: hb_frontend:latest
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 8086:3000
    depends_on:
      - server

  db:
    image: mariadb:latest
    restart: always
    ports:
      - 8087:3306
    volumes:
      - homeburrow-db:/var/lib/mysql

volumes:
  homeburrow-db: