services:
  server:
    env_file:
      - ./docker/db/.env
      - ./docker/server/.env
    volumes:
      - ./docker/server/docker-entrypoint-init.d:/docker-entrypoint-init.d
    command: server

  client:
    env_file:
      - ./docker/client/.env
    volumes:
      - ./docker/client/docker-entrypoint-init.d:/docker-entrypoint-init.d
    command: client

  db:
    image: mariadb:latest
    env_file:
      - ./docker/db/.env
    volumes:
      - ./docker/db/docker-entrypoint-init.d:/docker-entrypoint-initdb.d