version: '3.9'
services:
  server:
    env_file:
      - ./backend/.env
    build:
      context: .
      target: hb_back
    image: hb_backend:latest
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8085:8080
    command: go

  client:
    build:
      context: .
      target: hb_front
    image: hb_frontend:latest
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 8086:3000
    command: next

  db:
    image: mariadb
    restart: always
    env_file:
      - ./backend/.env
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    ports:
      - 8087:3306
    volumes:
      - homeburrow-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

volumes:
  homeburrow-db: