version: '3.9'
services:
  server:
    build:
      context: .
      target: hb_server
    image: hb_server:latest
    restart: always
    container_name: server
    volumes:
      - ./backend:/usr/src/app
      - ./docker/server/docker-entrypoint-init.d:/docker-entrypoint-init.d
    ports:
      - 8085:8080
    command: server
    depends_on:
      - db

  client:
    build:
      context: .
      target: hb_client
    image: hb_client:latest
    restart: always
    container_name: client
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules/
      - ./docker/client/docker-entrypoint-init.d:/docker-entrypoint-init.d
    ports:
      - 8086:3000
    command: client
    depends_on:
      - server

  db:
    image: mariadb:latest
    restart: always
    container_name: maria
    ports:
      - 8087:3306
    volumes:
      - homeburrow-db:/var/lib/mysql
      - ./docker/db/docker-entrypoint-init.d:/docker-entrypoint-initdb.d

volumes:
  homeburrow-db: