version: '3.9'
services:
  server:
    build:
      context: .
      target: hb_back
    image: hb_backend:latest
    volumes:
      - ./backend:/usr/src/app
      - ./docker-entrypoint.sh:/usr/src/app/docker-entrypoint.sh
    ports:
      - 8085:8080
    command: go
