name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: 
          docker run --network container:client appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8086/
          docker run --network container:client appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8085/api
