name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack and test
        run: 
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --build -d
          docker-compose exec server curl localhost:3000
          docker-compose exec server curl localhost:8080/api
